apiVersion: v2
name: grafana
description: A Helm umbrella chart for Grafana
type: application
version: 0.1.10

dependencies:
  - name: grafana
    version: "6.21.8"
    repository: "https://grafana.github.io/helm-charts"
