apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: git-server
  name: git-server
spec:
  selector:
    matchLabels:
      app: git-server
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: git-server
    spec:
      {{- with .Values.affinity }}
      affinity: 
{{ toYaml . | indent 8}}
      {{- end }}
      containers:
      - image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        name: git-server-nginx
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf 
          subPath: nginx.conf
          readOnly: true
          name: nginx-conf-volume
      - image: "{{ .Values.fcgi.image.repository }}:{{ .Values.fcgi.image.tag }}"
        imagePullPolicy: {{ .Values.fcgi.image.pullPolicy }}
        name: git-server-fcgi
        args: [ "{{ join " " .Values.repos }}" ]
        volumeMounts:
        - mountPath: /var/lib/git/
          name: git-server-repos
      volumes:
        - name: git-server-repos
          persistentVolumeClaim:
            claimName: git-server-data-pvc
        - name: nginx-conf-volume
          configMap:
            name: git-server-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
