apiVersion: v2
description: Manages a single Ceph cluster namespace for Rook
name: rook-ceph-cluster
version: 0.1.5

dependencies:
  - name: rook-ceph-cluster
    version: "1.7.2"
    repository: "https://charts.rook.io/release"
