apiVersion: v2
name: argo-cd-proxy-chart
description: A proxy helm chart for argo cd
type: application
version: 0.1.4

dependencies:
  - name: argo-cd
    version: "3.33.6"
    repository: "https://argoproj.github.io/argo-helm"
